### PR TITLE
econstruct, like scalaz.MonadError.emap

### LINKED ISSUE #118: CaseClass.constructEither
The current implementation of `CaseClass.construct` means that typeclasses that stop at `Functor` can be implemented (e.g. `Default`), but typeclasses with a `MonadError` (e.g. a JSON decoder) cannot.

The workaround is to use locally scoped exceptions, e.g.:

```scala
  private case class Fail(msg: String) extends Exception with NoStackTrace

  def combine[A](ctx: CaseClass[JsDecoder, A]): JsDecoder[A] = {
    case obj @ JsObject(_) =>
      try {
        val success = ctx.construct { p =>
          val value = obj.get(p.label).getOrElse(JsNull)
          p.typeclass.fromJson(value) match {
            case \/-(got)  => got
            case -\/(fail) => throw new Fail(fail) // scalafix:ok
          }
        }
        \/-(success)
      } catch {
        case Fail(msg) => -\/(msg)
      }
    case other => JsDecoder.fail("JsObject", other)
  }
```

it would be better if you allowed a traversal, even just for `Either`, allowing

```scala
  private case class Fail(msg: String) extends Exception with NoStackTrace

  def combine[A](ctx: CaseClass[JsDecoder, A]): JsDecoder[A] = {
    case obj @ JsObject(_) =>
        ctx.constructEither { p =>
          val value = obj.get(p.label).getOrElse(JsNull)
          p.typeclass.fromJson(value)
        }
    case other => JsDecoder.fail("JsObject", other)
  }
```

If you produced the boilerplate that called `.flatMap` then users could even use their own data types, not just `Either`.

### PR DESCRIPTION
**Pull request by fommil**
close #118

### CODE REVIEW

File: core/shared/src/main/scala/interface.scala [hunk 1]
```diff
@@ -155,6 +155,26 @@ abstract class CaseClass[Typeclass[_], Type] private[magnolia] (
...
+   * Like construct but allows each parameter to fail with an error.
+   *
+   * @see construct
+   */
+  final def econstruct[E <: AnyRef, Return](makeParam: Param[Typeclass, Type] => Either[E, Return]): Either[E, Type] = {
+    // poor man's scalaz.Traverse
+    try {
+      val bits = parameters.map { p =>
+        makeParam(p) match {
+          case Left(e) => throw EarlyExit(e)
```
Comment (propensive) [inline core/shared/src/main/scala/interface.scala]: `return Left(err.asInstanceOf[E])`, and remove the `try`/`catch`?

File: core/shared/src/main/scala/interface.scala [hunk 2]
```diff
@@ -155,6 +155,26 @@ abstract class CaseClass[Typeclass[_], Type] private[magnolia] (
...
 
+  /**
+   * Like construct but allows each parameter to fail with an error.
+   *
+   * @see construct
+   */
+  final def econstruct[E <: AnyRef, Return](makeParam: Param[Typeclass, Type] => Either[E, Return]): Either[E, Type] = {
+    // poor man's scalaz.Traverse
+    try {
+      val bits = parameters.map { p =>
```
Comment (propensive) [inline core/shared/src/main/scala/interface.scala]: `bits` is misleading, I think. How about writing it as a point-free expression as a way to avoid coming up with a unique name? ;)

File: core/shared/src/main/scala/interface.scala [hunk 3]
```diff
@@ -248,3 +268,5 @@ final case class TypeName(owner: String, short: String) {
   *                     whose full name contains the given [[String]]
   */
 final class debug(typeNamePart: String = "") extends scala.annotation.StaticAnnotation
+
+private[magnolia] final case class EarlyExit[E](e: E) extends Exception with util.control.NoStackTrace
```
Comment (propensive) [inline core/shared/src/main/scala/interface.scala]: I think that using `return` will avoid the stacktrace being generated too.

File: core/shared/src/main/scala/interface.scala (hunk 2 above)
Comment (propensive) [reply core/shared/src/main/scala/interface.scala]: I also don't think the name `econstruct` is clear enough. The `e` could stand for "either" or "exception". Let's go with `eitherConstruct`, unless you can suggest anything better...

File: core/shared/src/main/scala/interface.scala (hunk 1 above)
Comment (fommil) [reply core/shared/src/main/scala/interface.scala]: doesn't work, because the nearest method seems to be the map closure (I tried it)

**Comment by fommil** [comment]
@propensive changes made
